-- =========================================================
-- PORTAL NUMÉRICO - BASE DE DATOS DE APUNTES
-- Supabase / PostgreSQL
--
-- Ejecutar UNA SOLA VEZ desde:
-- Supabase > SQL Editor
-- =========================================================


-- 1. CREAR TABLA DE APUNTES
create table if not exists public.apuntes (
                                              id bigint generated by default as identity primary key,

                                              titulo text not null
                                              check (char_length(titulo) between 1 and 200),

    contenido text not null
    check (char_length(contenido) between 1 and 20000),

    created_at timestamptz not null default now()
    );


-- 2. ACTIVAR ROW LEVEL SECURITY (RLS)
alter table public.apuntes enable row level security;


-- =========================================================
-- POLÍTICA DE LECTURA
-- Todos los visitantes de la página pueden ver los apuntes.
-- =========================================================

drop policy if exists "apuntes_select_public"
on public.apuntes;

create policy "apuntes_select_public"
on public.apuntes
for select
                    to anon, authenticated
                    using (true);


-- =========================================================
-- POLÍTICA DE PUBLICACIÓN
-- Cualquier persona que tenga acceso a la página puede
-- publicar un apunte.
-- =========================================================

drop policy if exists "apuntes_insert_public"
on public.apuntes;

create policy "apuntes_insert_public"
on public.apuntes
for insert
to anon, authenticated
with check (true);


-- =========================================================
-- 3. COLUMNA PARA ARCHIVO ADJUNTO (PDF / Markdown)
-- =========================================================

alter table public.apuntes
add column if not exists archivo_url text;


-- =========================================================
-- 4. BUCKET DE STORAGE PARA ARCHIVOS DE APUNTES
-- Bucket publico: los archivos se sirven por URL publica.
-- =========================================================

insert into storage.buckets (id, name, public)
values ('archivos_apuntes', 'archivos_apuntes', true)
on conflict (id) do nothing;


-- =========================================================
-- POLITICAS DE STORAGE
-- Todos los visitantes pueden leer y subir archivos,
-- igual que con los apuntes (portal colaborativo de clase).
-- =========================================================

drop policy if exists "Archivos publicos"
on storage.objects;

create policy "Archivos publicos"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'archivos_apuntes');

drop policy if exists "Subir archivos"
on storage.objects;

create policy "Subir archivos"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'archivos_apuntes');


-- =========================================================
-- IMPORTANTE
--
-- NO damos permisos UPDATE ni DELETE públicamente.
--
-- Esto significa:
--
-- ✔ Todos pueden ver apuntes.
-- ✔ Todos pueden publicar apuntes.
-- ✘ Los visitantes no pueden modificar apuntes existentes.
-- ✘ Los visitantes no pueden borrar apuntes.
--
-- Si necesitas borrar algo, puedes hacerlo desde
-- el panel de Supabase.
-- =========================================================