-- =========================================================
-- PORTAL NUMÉRICO - BASE DE DATOS DE APUNTES
-- Supabase / PostgreSQL
--
-- Ejecutar UNA SOLA VEZ desde:
-- Supabase > SQL Editor
-- =========================================================


-- 1. CREAR TABLA DE APUNTES
create table if not exists public.apuntes (
                                              id bigint generated by default as identity primary key,

                                              titulo text not null
                                              check (char_length(titulo) between 1 and 200),

    contenido text not null
    check (char_length(contenido) between 1 and 20000),

    created_at timestamptz not null default now()
    );


-- 2. ACTIVAR ROW LEVEL SECURITY (RLS)
alter table public.apuntes enable row level security;


-- =========================================================
-- POLÍTICA DE LECTURA
-- Todos los visitantes de la página pueden ver los apuntes.
-- =========================================================

drop policy if exists "apuntes_select_public"
on public.apuntes;

create policy "apuntes_select_public"
on public.apuntes
for select
                    to anon, authenticated
                    using (true);


-- =========================================================
-- POLÍTICA DE PUBLICACIÓN
-- Cualquier persona que tenga acceso a la página puede
-- publicar un apunte.
-- =========================================================

drop policy if exists "apuntes_insert_public"
on public.apuntes;

create policy "apuntes_insert_public"
on public.apuntes
for insert
to anon, authenticated
with check (true);


-- =========================================================
-- IMPORTANTE
--
-- NO damos permisos UPDATE ni DELETE públicamente.
--
-- Esto significa:
--
-- ✔ Todos pueden ver apuntes.
-- ✔ Todos pueden publicar apuntes.
-- ✘ Los visitantes no pueden modificar apuntes existentes.
-- ✘ Los visitantes no pueden borrar apuntes.
--
-- Si necesitas borrar algo, puedes hacerlo desde
-- el panel de Supabase.
-- =========================================================